version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: last24_db
    restart: unless-stopped
    ports:
      - "33065:3306"
    environment:
      MYSQL_DATABASE: ultimahorabcn_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - last24_dbdata:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: last24_backend
    restart: unless-stopped
    ports:
      - "8055:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/.env:/app/.env
    depends_on:
      - db

  socket:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    container_name: last24_socket
    restart: unless-stopped
    ports:
      - "3055:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api
        VITE_SOCKET_URL: /
    container_name: last24_frontend
    restart: unless-stopped
    ports:
      - "5055:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
      - socket

volumes:
  last24_dbdata:
