version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: last24_db
    restart: unless-stopped
    ports:
      - "33065:3306"
    environment:
      MYSQL_DATABASE: ultimahorabcn_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - last24_dbdata:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: last24_backend
    restart: unless-stopped
    ports:
      - "8005:8000"
    # Volumes eliminats per producció (fem servir el codi dins la imatge)
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ultimahorabcn_db
      DB_USERNAME: root
      DB_PASSWORD: password
      FRONTEND_URL: https://last24bcn.daw.inspedralbes.cat
      CORS_ALLOWED_ORIGINS: https://last24bcn.daw.inspedralbes.cat
      GOOGLE_REDIRECT_URI: https://last24bcn.daw.inspedralbes.cat/api/auth/google/callback
    depends_on:
      - db

  socket:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    container_name: last24_socket
    restart: unless-stopped
    ports:
      - "3005:3001"
    # Volumes eliminats per producció

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: last24_frontend
    restart: unless-stopped
    volumes:
      - /var/www/last24bcn/dist:/app/dist
    # Volumes eliminats per producció
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=/api
      - VITE_SOCKET_URL=/
    depends_on:
      - backend
      - socket

volumes:
  last24_dbdata:
